#!/bin/sh

set -eu
OUT_DIR=/tmp/tidb_tools_test

if ! grep -Fq "$1" "$2"; then
    echo "TEST FAILED: OUTPUT DOES NOT CONTAIN '$1'"
    echo "____________________________________"
    cat "$2"
    echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
    exit 1
fi
