# Diff Configuration. This config file shows how to check data for DM's task.

######################### Global config #########################

# how many goroutines are created to check data
check-thread-count = 4

# set false if just want compare data by checksum, will skip select data when checksum is not equal.
# set true if want compare all different rows, will slow down the total compare time.
export-fix-sql = true

# ignore check table's data
check-struct-only = false

# dm-master's address, the format should like "http://127.0.0.1:8261"
dm-addr = "http://127.0.0.1:8261"

# the DM's task name which is willing to check data
dm-task = "test"

######################### Task config #########################
[task]
    # 1 fix sql: fix-target-TIDB1.sql
    # 2 log: sync-diff.log
    # 3 summary: summary.txt
    # 4 checkpoint: a dir
    output-dir = "/tmp/output/config"

    # tables need to check. *Include `schema` and `table`. Use `.` to split*
    target-check-tables = ["hb_test.*"]

