# Diff Configuration. This config file shows how to check data for DM's task.

######################### Global config #########################

log-level = "info"

# how many goroutines are created to check data
check-thread-count = 4

# sampling check percent, for example 10 means only check 10% data
sample-percent = 100

# set true if just want compare data by checksum, will skip select data when checksum is not equal.
compare-checksum-only = false

# set true will continue check from the latest checkpoint
use-checkpoint = true

# ignore check table's data
ignore-data-check = false

# ignore check table's struct
ignore-struct-check = false

# dm-master's address, the format should like "http://127.0.0.1:8261"
dm-addr = "http://127.0.0.1:8261"

# the DM's task name which is willing to check data
dm-task = "test"

######################### Task config #########################
[task]
    # 1 fix sql: fix-target-TIDB1.sql
    # 2 log: sync-diff.log
    # 3 summary: summary.txt
    # 4 checkpoint: a dir
    output-dir = "./output"

    # tables need to check. *Include `schema` and `table`. Use `.` to split*
    target-check-tables = ["hb_test.*"]

