# diff Configuration.

log-level = "info"

# for example, the whole data is [1...100]
# we can split these data to [1...10], [11...20], ..., [91...100]
# the [1...10] is a chunk, and it's chunk size is 10
# splited chunk's size
chunk-size = 1000

# how many goroutine created to check data
check-thread-count = 4

# sampling check percent, for example 10 means only check 10% data
sample = 100

# set true if target-db and source-db all support tidb implicit column "_tidb_rowid"
use-rowid = false

# the name of file which saves sqls used to fix different data
fix-sql-file = "fix.sql"

# use tidb's snapshot data, sql looks like set @@tidb_snapshot="2016-10-08 16:45:26"
source-snapshot = "2016-10-08 16:45:26"
target-snapshot = "2016-10-08 16:45:26"

# if check-table is nil, will check all tables in the schema.
[[check-table]]
# table name.
name = "test"

# field should be the primary key, unique key or field with index. 
# if comment this, diff will find a suitable field.
field = "id"

# check data's range
# range = "age > 10 AND age < 20"

[source-db]
host = "127.0.0.1"
user = "root"
password = ""
# schema name
name = "test"
port = 3306

[target-db]
host = "127.0.0.1"
user = "root"
password = ""
# schema name
name = "test"
port = 4000