---
# Common Tasks

- name: create deploy directories
  file: path={{ item }} state=directory mode=0755
  with_items:
    - "{{ deploy_dir }}/bin"
    - "{{ deploy_dir }}/scripts"
    - "{{ deploy_dir }}/conf"
    - "{{ deploy_dir }}/meta"
    - "{{ deploy_dir }}/log"
    - "{{ deploy_dir }}/data"
    - "{{ backup_dir }}"


