--- 


- hosts: syncer_servers
  tags: ['syncer', 'never']
  tasks:
    - name: stop syncer by systemd
      become: true
      systemd: name=syncer-{{ job_name }}.service state=stopped enabled=no

    - name: wait for syncer down
      wait_for: host={{ ansible_host }} port={{ syncer_status_port }} state=stopped


- hosts: mydumper_servers
  tags: ['mydumper', 'never']
  tasks:
    - name: stop mydumper by systemd
      become: true
      systemd: name=mydumper-{{ job_name }}.service state=stopped enabled=no

- hosts: loader_servers
  tags: ['loader', 'never']
  tasks:
    - name: stop loader by systemd
      become: true
      systemd: name=loader-{{ job_name }}.service state=stopped enabled=no

- hosts: integrated_servers
  tags: ['integrated', 'never']
  tasks:
    - name: start integrated script by systemd
      become: true
      systemd: name=integrated-{{ job_name }}.service state=stopped enabled=no