# sync_check Configuration.

log-level = "info"

# for example, the whole data is [1...100]
# we can split these data to [1...10], [11...20], ..., [91...100]
# the [1...10] is a chunk, and it's chunk size is 10
# splited chunk's size
chunk-size = 1000

# how many goroutine created to check data
check-thcount = 4

# use split-field to split data to several chunk
#split-field = "id"

# sampling check percent, for example 10 means only check 10% data
sample = 100

# set true if target-db and source-db all support tidb implicit column "_tidb_rowid"
use-rowid = false

# fix different data in target-db if fix_data is true, must have primary key or unique key
fix-data = false

snapshot = "2018-05-17 00:30:00"

# if check-table is nil, will check all tables in the schema. 
[[check-table]]
# table name.
name = "equal"

# field should be the primary key, unique key or field with index. 
# if comment this, sync_check will find a suitable field.
#field = "id"

# check data's range
# range = "age > 10 AND age < 20"

[target-db]
host = "192.168.1.29"
user = "root"
password = ""
# schema name
name = "test"
port = 4001

[source-db]
host = "192.168.1.29"
user = "root"
password = "123456"
# schema name
name = "test"
port = 3307
